### ISSUE TITLE
Edge IE Mode Automation - ".navigate" method

### ISSUE THREAD

**Issue by YN32** [longvh211/Edge-IE-Mode-Automation-with-IES-for-VBA#3]
Anh Long,

I do have another question:  The ".navigate" method is from the MSHTHM Reference.  How do I reference it so I can use this method in IE mode?  I noticed that you can reference it for HTMLDocument as in Dim TargetWebDoc As MSHTML.HTMLDocument
 
Do I need to declare any other references in order to use ".navigate" and ".refresh" methods?  If it cannot be done in IE Mode, can UIA simulates this method?  The reason why I need these methods is because the website that I am working on contains layers of drill-down menu.  Since I know the URL of the page that I wanted to select, I would like to navigate directly to the webpage instead of accessing multiple links in order to get to it.

**Comment by longvh211** [comment]
Hi Dung,

You can use this method: **document.location.href = (target URL)**.  

For example, the DemoWithUIE procedure can add this line at the end to make the IE Mode window navigate to Yahoo:

`ieDoc.location.href = "https://sg.yahoo.com/?p=us"`

Make sure to include the full URL path, including "https".

**Comment by YN32** [comment]
Thank you!
For the .refresh method, would it be "document.location.href.refresh"?
Reason for the .refresh method:   The website that I interact with, often has "Page can not be display".  Thus, in my old codes, I have to refresh 3 to 5 times (depending on the time of the day) before I can sign into the webiste.


    On Wednesday, September 7, 2022 at 09:00:55 PM PDT, Long Vh ***@***.***> wrote:  
 
 


Hi Dung,

You can use this method: document.location.href = (target URL).

For example, the DemoWithUIE procedure can add this line at the end to make the found IE Mode window navigate to Yahoo:

ieDoc.location.href = "https://sg.yahoo.com/?p=us"

**Comment by longvh211** [comment]
That seems like a server issue. Anyway, you can try **document.location.reload**

**Comment by YN32** [comment]
I hope I do not jinx it, but this is all I need to complete my conversion to work with IE Mode in Edge.  Thanks again for taking the time to share your knowledge with us.

**Comment by nareshdeee10** [comment]
> That seems like a server issue. Anyway, you can try **document.location.reload**

Hi Longvh211 - How we need to fire events ( on change fire event in normal IE) or fire the JS.?

**Comment by nareshdeee10** [comment]
Hi Longvh211 - How we need to fire events ( on change fire event in normal IE) or fire the JS.?

**Comment by longvh211** [comment]
> Hi Longvh211 - How we need to fire events ( on change fire event in normal IE) or fire the JS.?

Naresh, try to open in a new issue thread instead to keep it separate from this one.

**Comment by nareshdeee10** [comment]
> > Hi Longvh211 - How we need to fire events ( on change fire event in normal IE) or fire the JS.?
> 
> Naresh, try to open in a new issue thread instead to keep it separate from this one.

Sure Thank you!
